// ---- DON'T EDIT! THIS IS AUTO GENERATED CODE ---- //
use crate::lexers::Token;

pub fn get_keyword_token(identifier: &Vec<char>) -> Result<Token, String> {
    let id: String = identifier.into_iter().collect();
    match &id[..] {
        "True" => Ok(Token::CONSTANT(identifier.to_vec())),
        "False" => Ok(Token::CONSTANT(identifier.to_vec())),
        "return" => Ok(Token::CONSTANT(identifier.to_vec())),
        "mempty" => Ok(Token::CONSTANT(identifier.to_vec())),
        "not" => Ok(Token::CONSTANT(identifier.to_vec())),
        "foldr" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Map" => Ok(Token::CONSTANT(identifier.to_vec())),
        "lookup" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Left" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Right" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Walk" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Char" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Bool" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Maybe" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Int" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Prelude" => Ok(Token::CONSTANT(identifier.to_vec())),
        "any" => Ok(Token::CONSTANT(identifier.to_vec())),
        "filter" => Ok(Token::CONSTANT(identifier.to_vec())),
        "map" => Ok(Token::CONSTANT(identifier.to_vec())),
        "init" => Ok(Token::CONSTANT(identifier.to_vec())),
        "null" => Ok(Token::CONSTANT(identifier.to_vec())),
        "last" => Ok(Token::CONSTANT(identifier.to_vec())),
        "unwords" => Ok(Token::CONSTANT(identifier.to_vec())),
        "otherwise" => Ok(Token::CONSTANT(identifier.to_vec())),
        "either" => Ok(Token::CONSTANT(identifier.to_vec())),
        "const" => Ok(Token::CONSTANT(identifier.to_vec())),
        "fmap" => Ok(Token::CONSTANT(identifier.to_vec())),
        "take" => Ok(Token::CONSTANT(identifier.to_vec())),
        "max" => Ok(Token::CONSTANT(identifier.to_vec())),
        "putStrLn" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Bibtex" => Ok(Token::ENTITYTAG(identifier.to_vec())),
        "Biblatex" => Ok(Token::ENTITYTAG(identifier.to_vec())),
        "Nothing" => Ok(Token::ENTITYTAG(identifier.to_vec())),
        "Just" => Ok(Token::ENTITYTAG(identifier.to_vec())),
        "Str" => Ok(Token::ENTITYTAG(identifier.to_vec())),
        "Space" => Ok(Token::ENTITYTAG(identifier.to_vec())),
        "FancyVal" => Ok(Token::ENTITYTAG(identifier.to_vec())),
        "BibState" => Ok(Token::ENTITYTAG(identifier.to_vec())),
        "Many" => Ok(Token::ENTITYTAG(identifier.to_vec())),
        "as" => Ok(Token::KEYWORD(identifier.to_vec())),
        "import" => Ok(Token::KEYWORD(identifier.to_vec())),
        "type" => Ok(Token::KEYWORD(identifier.to_vec())),
        "case" => Ok(Token::KEYWORD(identifier.to_vec())),
        "do" => Ok(Token::KEYWORD(identifier.to_vec())),
        "of" => Ok(Token::KEYWORD(identifier.to_vec())),
        "if" => Ok(Token::KEYWORD(identifier.to_vec())),
        "then" => Ok(Token::KEYWORD(identifier.to_vec())),
        "else" => Ok(Token::KEYWORD(identifier.to_vec())),
        "let" => Ok(Token::KEYWORD(identifier.to_vec())),
        "in" => Ok(Token::KEYWORD(identifier.to_vec())),
        "module" => Ok(Token::KEYWORD(identifier.to_vec())),
        "qualified" => Ok(Token::KEYWORD(identifier.to_vec())),
        "where" => Ok(Token::KEYWORD(identifier.to_vec())),
        "LANGUAGE" => Ok(Token::KEYWORD(identifier.to_vec())),
        "OPTIONS_GHC" => Ok(Token::KEYWORD(identifier.to_vec())),
        "hiding" => Ok(Token::KEYWORD(identifier.to_vec())),
        "data" => Ok(Token::KEYWORD(identifier.to_vec())),
        "deriving" => Ok(Token::KEYWORD(identifier.to_vec())),
        _ => Err(String::from("Not a keyword")),
    }
}
