// ---- DON'T EDIT! THIS IS AUTO GENERATED CODE ---- //
#[derive(PartialEq, Debug)]
pub enum Token {
    ILLEGAL,
    EOF,
    ENDL(char),
    IDENT(Vec<char>),
    INT(Vec<char>),
    ENTITY(Vec<char>),
    STRING(Vec<char>),
    CONSTANT(Vec<char>),
    KEYWORD(Vec<char>),
    COMMENT(Vec<char>),
}

pub fn get_keyword_token(identifier: &Vec<char>) -> Result<Token, String> {
    let id: String = identifier.into_iter().collect();
    match &id[..] {
        "nil" => Ok(Token::CONSTANT(identifier.to_vec())),
        "true" => Ok(Token::CONSTANT(identifier.to_vec())),
        "false" => Ok(Token::CONSTANT(identifier.to_vec())),
        "addr" => Ok(Token::KEYWORD(identifier.to_vec())),
        "and" => Ok(Token::KEYWORD(identifier.to_vec())),
        "as" => Ok(Token::KEYWORD(identifier.to_vec())),
        "asm" => Ok(Token::KEYWORD(identifier.to_vec())),
        "bind" => Ok(Token::KEYWORD(identifier.to_vec())),
        "block" => Ok(Token::KEYWORD(identifier.to_vec())),
        "break" => Ok(Token::KEYWORD(identifier.to_vec())),
        "case" => Ok(Token::KEYWORD(identifier.to_vec())),
        "cast" => Ok(Token::KEYWORD(identifier.to_vec())),
        "concept" => Ok(Token::KEYWORD(identifier.to_vec())),
        "const" => Ok(Token::KEYWORD(identifier.to_vec())),
        "continue" => Ok(Token::KEYWORD(identifier.to_vec())),
        "converter" => Ok(Token::KEYWORD(identifier.to_vec())),
        "defer" => Ok(Token::KEYWORD(identifier.to_vec())),
        "discard" => Ok(Token::KEYWORD(identifier.to_vec())),
        "distinct" => Ok(Token::KEYWORD(identifier.to_vec())),
        "div" => Ok(Token::KEYWORD(identifier.to_vec())),
        "do" => Ok(Token::KEYWORD(identifier.to_vec())),
        "elif" => Ok(Token::KEYWORD(identifier.to_vec())),
        "else" => Ok(Token::KEYWORD(identifier.to_vec())),
        "echo" => Ok(Token::KEYWORD(identifier.to_vec())),
        "end" => Ok(Token::KEYWORD(identifier.to_vec())),
        "enum" => Ok(Token::KEYWORD(identifier.to_vec())),
        "except" => Ok(Token::KEYWORD(identifier.to_vec())),
        "export" => Ok(Token::KEYWORD(identifier.to_vec())),
        "finally" => Ok(Token::KEYWORD(identifier.to_vec())),
        "for" => Ok(Token::KEYWORD(identifier.to_vec())),
        "from" => Ok(Token::KEYWORD(identifier.to_vec())),
        "func" => Ok(Token::KEYWORD(identifier.to_vec())),
        "if" => Ok(Token::KEYWORD(identifier.to_vec())),
        "import" => Ok(Token::KEYWORD(identifier.to_vec())),
        "in" => Ok(Token::KEYWORD(identifier.to_vec())),
        "include" => Ok(Token::KEYWORD(identifier.to_vec())),
        "interface" => Ok(Token::KEYWORD(identifier.to_vec())),
        "is" => Ok(Token::KEYWORD(identifier.to_vec())),
        "isnot" => Ok(Token::KEYWORD(identifier.to_vec())),
        "iterator" => Ok(Token::KEYWORD(identifier.to_vec())),
        "let" => Ok(Token::KEYWORD(identifier.to_vec())),
        "macro" => Ok(Token::KEYWORD(identifier.to_vec())),
        "method" => Ok(Token::KEYWORD(identifier.to_vec())),
        "mixin" => Ok(Token::KEYWORD(identifier.to_vec())),
        "mod" => Ok(Token::KEYWORD(identifier.to_vec())),
        "not" => Ok(Token::KEYWORD(identifier.to_vec())),
        "notin" => Ok(Token::KEYWORD(identifier.to_vec())),
        "object" => Ok(Token::KEYWORD(identifier.to_vec())),
        "of" => Ok(Token::KEYWORD(identifier.to_vec())),
        "or" => Ok(Token::KEYWORD(identifier.to_vec())),
        "out" => Ok(Token::KEYWORD(identifier.to_vec())),
        "proc" => Ok(Token::KEYWORD(identifier.to_vec())),
        "ptr" => Ok(Token::KEYWORD(identifier.to_vec())),
        "raise" => Ok(Token::KEYWORD(identifier.to_vec())),
        "ref" => Ok(Token::KEYWORD(identifier.to_vec())),
        "return" => Ok(Token::KEYWORD(identifier.to_vec())),
        "shl" => Ok(Token::KEYWORD(identifier.to_vec())),
        "shr" => Ok(Token::KEYWORD(identifier.to_vec())),
        "static" => Ok(Token::KEYWORD(identifier.to_vec())),
        "template" => Ok(Token::KEYWORD(identifier.to_vec())),
        "try" => Ok(Token::KEYWORD(identifier.to_vec())),
        "tuple" => Ok(Token::KEYWORD(identifier.to_vec())),
        "type" => Ok(Token::KEYWORD(identifier.to_vec())),
        "using" => Ok(Token::KEYWORD(identifier.to_vec())),
        "var" => Ok(Token::KEYWORD(identifier.to_vec())),
        "when" => Ok(Token::KEYWORD(identifier.to_vec())),
        "while" => Ok(Token::KEYWORD(identifier.to_vec())),
        "yield" => Ok(Token::KEYWORD(identifier.to_vec())),
        "xor" => Ok(Token::KEYWORD(identifier.to_vec())),
        "int" => Ok(Token::KEYWORD(identifier.to_vec())),
        "int8" => Ok(Token::KEYWORD(identifier.to_vec())),
        "int16" => Ok(Token::KEYWORD(identifier.to_vec())),
        "int32" => Ok(Token::KEYWORD(identifier.to_vec())),
        "int64" => Ok(Token::KEYWORD(identifier.to_vec())),
        "uint" => Ok(Token::KEYWORD(identifier.to_vec())),
        "uint8" => Ok(Token::KEYWORD(identifier.to_vec())),
        "uint16" => Ok(Token::KEYWORD(identifier.to_vec())),
        "uint32" => Ok(Token::KEYWORD(identifier.to_vec())),
        "uint64" => Ok(Token::KEYWORD(identifier.to_vec())),
        "float" => Ok(Token::KEYWORD(identifier.to_vec())),
        "float32" => Ok(Token::KEYWORD(identifier.to_vec())),
        "float64" => Ok(Token::KEYWORD(identifier.to_vec())),
        "char" => Ok(Token::KEYWORD(identifier.to_vec())),
        "string" => Ok(Token::KEYWORD(identifier.to_vec())),
        "cstring" => Ok(Token::KEYWORD(identifier.to_vec())),
        "bool" => Ok(Token::KEYWORD(identifier.to_vec())),
        _ => Err(String::from("Not a keyword")),
    }
}
