// ---- DON'T EDIT! THIS IS AUTO GENERATED CODE ---- //
use crate::lexers::Token;

pub fn get_keyword_token(identifier: &Vec<char>) -> Result<Token, String> {
    let id: String = identifier.into_iter().collect();
    match &id[..] {
        "true" => Ok(Token::CONSTANT(identifier.clone())),
        "false" => Ok(Token::CONSTANT(identifier.clone())),
        "NULL" => Ok(Token::CONSTANT(identifier.clone())),
        "size_t" => Ok(Token::CONSTANT(identifier.clone())),
        "asm" => Ok(Token::KEYWORD(identifier.clone())),
        "const" => Ok(Token::KEYWORD(identifier.clone())),
        "char" => Ok(Token::KEYWORD(identifier.clone())),
        "case" => Ok(Token::KEYWORD(identifier.clone())),
        "catch" => Ok(Token::KEYWORD(identifier.clone())),
        "continue" => Ok(Token::KEYWORD(identifier.clone())),
        "do" => Ok(Token::KEYWORD(identifier.clone())),
        "default" => Ok(Token::KEYWORD(identifier.clone())),
        "define" => Ok(Token::KEYWORD(identifier.clone())),
        "delete" => Ok(Token::KEYWORD(identifier.clone())),
        "double" => Ok(Token::KEYWORD(identifier.clone())),
        "else" => Ok(Token::KEYWORD(identifier.clone())),
        "extern" => Ok(Token::KEYWORD(identifier.clone())),
        "enum" => Ok(Token::KEYWORD(identifier.clone())),
        "float" => Ok(Token::KEYWORD(identifier.clone())),
        "goto" => Ok(Token::KEYWORD(identifier.clone())),
        "for" => Ok(Token::KEYWORD(identifier.clone())),
        "if" => Ok(Token::KEYWORD(identifier.clone())),
        "ifdef" => Ok(Token::KEYWORD(identifier.clone())),
        "ifndef" => Ok(Token::KEYWORD(identifier.clone())),
        "endif" => Ok(Token::KEYWORD(identifier.clone())),
        "long" => Ok(Token::KEYWORD(identifier.clone())),
        "return" => Ok(Token::KEYWORD(identifier.clone())),
        "int" => Ok(Token::KEYWORD(identifier.clone())),
        "include" => Ok(Token::KEYWORD(identifier.clone())),
        "inline" => Ok(Token::KEYWORD(identifier.clone())),
        "unsigned" => Ok(Token::KEYWORD(identifier.clone())),
        "union" => Ok(Token::KEYWORD(identifier.clone())),
        "break" => Ok(Token::KEYWORD(identifier.clone())),
        "void" => Ok(Token::KEYWORD(identifier.clone())),
        "volatile" => Ok(Token::KEYWORD(identifier.clone())),
        "register" => Ok(Token::KEYWORD(identifier.clone())),
        "signed" => Ok(Token::KEYWORD(identifier.clone())),
        "static" => Ok(Token::KEYWORD(identifier.clone())),
        "struct" => Ok(Token::KEYWORD(identifier.clone())),
        "sizeof" => Ok(Token::KEYWORD(identifier.clone())),
        "short" => Ok(Token::KEYWORD(identifier.clone())),
        "switch" => Ok(Token::KEYWORD(identifier.clone())),
        "typedef" => Ok(Token::KEYWORD(identifier.clone())),
        "try" => Ok(Token::KEYWORD(identifier.clone())),
        "throw" => Ok(Token::KEYWORD(identifier.clone())),
        "while" => Ok(Token::KEYWORD(identifier.clone())),
        _ => Err(String::from("Not a keyword")),
    }
}
