// ---- DON'T EDIT! THIS IS AUTO GENERATED CODE ---- //
use crate::lexers::Token;

pub fn get_keyword_token(identifier: &Vec<char>) -> Result<Token, String> {
    let id: String = identifier.into_iter().collect();
    match &id[..] {
        "true" => Ok(Token::CONSTANT(identifier.to_vec())),
        "false" => Ok(Token::CONSTANT(identifier.to_vec())),
        "Rails" => Ok(Token::VAR(identifier.to_vec())),
        "alias" => Ok(Token::KEYWORD(identifier.to_vec())),
        "and" => Ok(Token::KEYWORD(identifier.to_vec())),
        "BEGIN" => Ok(Token::KEYWORD(identifier.to_vec())),
        "begin" => Ok(Token::KEYWORD(identifier.to_vec())),
        "break" => Ok(Token::KEYWORD(identifier.to_vec())),
        "case" => Ok(Token::KEYWORD(identifier.to_vec())),
        "class" => Ok(Token::KEYWORD(identifier.to_vec())),
        "def" => Ok(Token::KEYWORD(identifier.to_vec())),
        "defined?" => Ok(Token::KEYWORD(identifier.to_vec())),
        "do" => Ok(Token::KEYWORD(identifier.to_vec())),
        "else" => Ok(Token::KEYWORD(identifier.to_vec())),
        "elsif" => Ok(Token::KEYWORD(identifier.to_vec())),
        "END" => Ok(Token::KEYWORD(identifier.to_vec())),
        "end" => Ok(Token::KEYWORD(identifier.to_vec())),
        "ensure" => Ok(Token::KEYWORD(identifier.to_vec())),
        "for" => Ok(Token::KEYWORD(identifier.to_vec())),
        "if" => Ok(Token::KEYWORD(identifier.to_vec())),
        "in" => Ok(Token::KEYWORD(identifier.to_vec())),
        "module" => Ok(Token::KEYWORD(identifier.to_vec())),
        "next" => Ok(Token::KEYWORD(identifier.to_vec())),
        "nil" => Ok(Token::KEYWORD(identifier.to_vec())),
        "not" => Ok(Token::KEYWORD(identifier.to_vec())),
        "or" => Ok(Token::KEYWORD(identifier.to_vec())),
        "private" => Ok(Token::KEYWORD(identifier.to_vec())),
        "redo" => Ok(Token::KEYWORD(identifier.to_vec())),
        "rescue" => Ok(Token::KEYWORD(identifier.to_vec())),
        "retry" => Ok(Token::KEYWORD(identifier.to_vec())),
        "return" => Ok(Token::KEYWORD(identifier.to_vec())),
        "self" => Ok(Token::KEYWORD(identifier.to_vec())),
        "super" => Ok(Token::KEYWORD(identifier.to_vec())),
        "then" => Ok(Token::KEYWORD(identifier.to_vec())),
        "undef" => Ok(Token::KEYWORD(identifier.to_vec())),
        "unless" => Ok(Token::KEYWORD(identifier.to_vec())),
        "until" => Ok(Token::KEYWORD(identifier.to_vec())),
        "when" => Ok(Token::KEYWORD(identifier.to_vec())),
        "while" => Ok(Token::KEYWORD(identifier.to_vec())),
        "yield" => Ok(Token::KEYWORD(identifier.to_vec())),
        _ => Err(String::from("Not a keyword")),
    }
}
