hashtag_comment: true

constant:
  PHONY: PHONY
  call: call
  cd: cd
  command: command
  test: test
  echo: echo
  shell: shell
  MAKE: MAKE

entity_suffix:
  colon: ":"

keyword:
  "export": "export"
  "include": "include"

condition:
  ACCEPT_ESCAPED_STRING: true
  ACCEPT_STRING_ONE_QUOTE: true
  ACCEPT_STRING_DOUBLE_QUOTE: true
  ACCEPT_CHAR_IDENTIFIER: "-.@"
  ACCEPT_ENTITY_TAG_SUFFIX: "is_digit(self.ch)"
  BREAK_ENTITY_TAG_SUFFIX: "!is_digit(self.ch) && !is_letter(self.ch)"
  MARK_AS_IDENT_ON_CHAR: "@"