pub mod lexers;
use crate::lexers::*;

pub fn render_html(input: Vec<char>, lang: &str) -> String {
    return match lang {
        "actionscript" => actionscript::render::render_html(input),
        "bash" => bash::render::render_html(input),
        "c" => c::render::render_html(input),
        "clojure" => clojure::render::render_html(input),
        "css" => css::render::render_html(input),
        "cuda" => cuda::render::render_html(input),
        "dart" => dart::render::render_html(input),
        "edn" => edn::render::render_html(input),
        "erlang" => erlang::render::render_html(input),
        "cpp" => cpp::render::render_html(input),
        "cs" => cs::render::render_html(input),
        "go" => go::render::render_html(input),
        "groovy" => groovy::render::render_html(input),
        "haskell" => haskell::render::render_html(input),
        "html" => html::render::render_html(input),
        "java" => java::render::render_html(input),
        "javascript" => javascript::render::render_html(input),
        "json" => json::render::render_html(input),
        "lua" => lua::render::render_html(input),
        "makefile" => makefile::render::render_html(input),
        "markdown" => markdown::render::render_html(input),
        "nim" => nim::render::render_html(input),
        "php" => php::render::render_html(input),
        "python" => python::render::render_html(input),
        "raw" => raw::render::render_html(input),
        "ruby" => ruby::render::render_html(input),
        "rust" => rust::render::render_html(input),
        "toml" => toml::render::render_html(input),
        "typescript" => typescript::render::render_html(input),
        "vue" => vue::render::render_html(input),
        "yaml" => yaml::render::render_html(input),
        "zig" => zig::render::render_html(input),
        "kotlin" => kotlin::render::render_html(input),
        _ => String::new(),
    };
}
