[package]
name = "test-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13"
actix-web = "4"
actix-web-actors = "4.1"

[lib]
name = "test_server"
bench = false

[[bin]]
name = "hl-server"
path = "src/main.rs"
